name: chronos_apex
description: The Chronos Apex Productivity Hub.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0

flutter:
  uses-material-design: true
